name: Build LaTeX PDF

on:
  push:
    branches:
      - main  # Change this to your working branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up LaTeX
      run: sudo apt-get install -y texlive-xetex texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

    - name: Compile LaTeX document
      run: xelatex main.tex  # Use xelatex instead of pdflatex

    - name: Upload to Dropbox
      run: |
        curl -X POST https://content.dropboxapi.com/2/files/upload \
        --header "Authorization: Bearer ${{ secrets.DROPBOX_ACCESS_TOKEN }}" \
        --header "Dropbox-API-Arg: {\"path\": \"/Academic_CV/Anirudh_Salgundi_CV.pdf\",\"mode\": \"overwrite\"}" \
        --header "Content-Type: application/octet-stream" \
        --data-binary @./main.pdf
